zuul:
  prefix: /api
  ignoredServices: '*'
  routes:
    authentication-server: /authentication-server/**
    visits-service: /visit/**
    customers-service: /customer/**
    api-gateway: /gateway/**

server:
  port: 9090
  compression:
    enabled: true
    mime-types: application/json,text/css,application/javascript
    min-response-size: 2048

# Internationalization
spring.messages.basename: messages/messages

eureka:
  instance:
      instance-id: ${spring.application.name}:${random.uuid}
---
spring:
  config:
    activate:
      on-profile: docker
  #zipkin:
    #baseUrl: http://tracing-server:9411
eureka:
  instance:
      hostname: localhost
      instance-id: ${spring.application.name}:${random.uuid}
      prefer-ip-address: true 
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/
