
spring:
  application:
    name: authentication-server
  main:
    #web-application-type: reactive
    allow-bean-definition-overriding: true
  #zipkin:
    #baseUrl: http://tracing-server:9411
  datasource:
    initialization-mode: always
    driver-class-name: com.mysql.cj.jdbc.Driver
    platform: mysql ${MYSQL_HOST:localhost:3306}
    url: jdbc:mysql://${MYSQL_HOST:localhost:3306}/zibra_${spring.application.name}_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: my_secret_password
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update  #none #drop #create #create-only #create-drop #update #validate
  sql:
    init:
      mode: always
#     schema-locations: classpath*:db/mysql/schema.sql
#     data-locations: classpath*:db/mysql/data.sql      
    show-sql: false
  mail:
    host: localhost
    port: 1025
    protocol: smtp
    username: ""
    password: ""
    templates:
      path : mail-templates
    properties:
      mail:
        debug: true
        transport:
          protocol: smtp
        smtps:
          auth: true
          starttls:
            enable: true
            timeout: 8000
        smtp:
          auth: false
          starttls:
            enable: false
            timeout: 8000    


################### App  variables  ########################################

app:    
  jwt:
    # Signing key for HS512 algorithm
    # In http://www.allkeysgenerator.com/ you can generate all kinds of keys
    secret: v9y$B&E)H@MbQeThWmZq4t7w!z%C*F-JaNdRfUjXn2r5u8x/A?D(G+KbPeShVkYp
    expiration:
      minutes: 10
  cors:
    allowed-origins: http://localhost:3000
    
################### JavaMail Configuration ##########################
support:
  email: support@gmail.com
 
################### geoip2 Configuration ##########################   
geo:
  ip:
    lib:
      enabled: false
################### cron Configuration ########################## 
purge:
  cron:
    expression: 0 0 1 * * ?
    
################### Eureka commun config  #########################
eureka:
  instance:
      hostname: localhost
      instance-id: ${spring.application.name}:${random.uuid}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#####################################################################

########################Amazon S3 Storages####################################

minio:
  endPoint:  http://localhost:9000   
  accessKey: by3DztiTX6g1TAfw
  secretKey: DlglXeoUqBOrzF5tvwfy4golKb6A6R7i
  bucketName: mybucket
  
localFileFolder: C:\test\\files\\