server:
  port: 8761

spring:
  application:
    name: discovery-server

env:
  eureka:
    user: ${EUREKA_USER:user}
    password: ${EUREKA_PASSWORD:password}
    
    
eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${random.uuid}
  # standalone mode
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
