server:
  port : 9090


spring:
  application:
    name: gateway
  devtools:
    livereload:
      port: 35730
  jmx:
    enabled: true
   #zipkin:
      #base-url:  http://127.0.0.2:9411
   #sleuth:
      #reactor:
         #instrumentation-type: decorate-on-each
  cloud:
        gateway:
            discovery:
               locator:
                  enabled: true
                  lower-case-service-id: true    
 
# Internationalization
spring.messages.basename: messages/messages

################### Eureka commun config  #########################
eureka:
  instance:
      hostname: localhost
      instance-id: ${spring.application.name}:${random.uuid}
---
spring:
  config:
    activate:
      on-profile: docker
  #zipkin:
    #baseUrl: http://tracing-server:9411
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/